"$schema" = "https://schema.tauri.app/config/2"
productName = "pix-wallet"
version = "0.1.0"
identifier = "com.tcyeee.pix-wallet"

[build]
beforeDevCommand = "pnpm dev"
devUrl = "http://localhost:1420"
beforeBuildCommand = "pnpm build"
frontendDist = "../dist"

[app]
# 启用前瞻接口,启用以后,无法上架App Store
macOSPrivateApi = false

[[app.windows]]
title = ""
# 顶部工具栏
decorations = true
# 背景透明
transparent = true
width = 900
height = 600
minWidth = 820
minHeight = 600
# 启动时候不再显示窗口
incognito = true

[app.security]
csp = ""

[bundle]
active = true
targets = "all"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico",
]
